In [1]:
! pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 16 kB/s 
     |████████████████████████████████| 438 kB 64.8 MB/s 
     |████████████████████████████████| 1.7 MB 51.2 MB/s 
     |████████████████████████████████| 5.9 MB 51.9 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5

In [2]:
import tensorflow as tf
print(tf.__version__)


2.10.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences 
sent=['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'I would like to travel'] 

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'I would like to travel']

In [6]:
#voclabery size
voc_size=500

In [8]:
one_hot_resp=[one_hot(words,voc_size) for words in sent]
one_hot_resp

[[301, 345, 477, 393],
 [301, 345, 477, 228],
 [301, 266, 477, 361],
 [220, 371, 118, 323, 172],
 [220, 371, 118, 323, 226],
 [260, 301, 251, 477, 69],
 [220, 497, 111, 47, 316]]

Word2Vec(Word embedding)

In [9]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential 

In [14]:
sent_length=8 
embedded_docs=pad_sequences(one_hot_resp,padding='pre',maxlen=sent_length) # padding = 'pre'/'post' 
embedded_docs

array([[  0,   0,   0,   0, 301, 345, 477, 393],
       [  0,   0,   0,   0, 301, 345, 477, 228],
       [  0,   0,   0,   0, 301, 266, 477, 361],
       [  0,   0,   0, 220, 371, 118, 323, 172],
       [  0,   0,   0, 220, 371, 118, 323, 226],
       [  0,   0,   0, 260, 301, 251, 477,  69],
       [  0,   0,   0, 220, 497, 111,  47, 316]], dtype=int32)

In [11]:
dim=10 
model= Sequential() 
model.add(Embedding(voc_size,dim,input_length=sent_length)) 
model.compile('adam','mse') 

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
embedded_docs[0]

array([  0,   0,   0,   0, 301, 345, 477, 393], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 71ms/step


array([[ 0.0002228 , -0.02179424,  0.02515132,  0.03432262, -0.01475636,
        -0.04662099,  0.03580693,  0.01218406,  0.04421878, -0.00967856],
       [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262, -0.01475636,
        -0.04662099,  0.03580693,  0.01218406,  0.04421878, -0.00967856],
       [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262, -0.01475636,
        -0.04662099,  0.03580693,  0.01218406,  0.04421878, -0.00967856],
       [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262, -0.01475636,
        -0.04662099,  0.03580693,  0.01218406,  0.04421878, -0.00967856],
       [ 0.04556483,  0.0287129 , -0.0244712 ,  0.04458561, -0.01200197,
        -0.0093414 , -0.03454223, -0.03976092,  0.04076023, -0.04271444],
       [-0.00312374,  0.03127487,  0.04706002,  0.04473511, -0.02143162,
        -0.04631407, -0.02680214, -0.0285754 ,  0.01728689, -0.00047459],
       [-0.00547457, -0.03071852,  0.00469918,  0.00037831,  0.03611156,
         0.04549691,  0.02106358, -0.04152339

In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 37ms/step


array([[[ 0.0002228 , -0.02179424,  0.02515132,  0.03432262,
         -0.01475636, -0.04662099,  0.03580693,  0.01218406,
          0.04421878, -0.00967856],
        [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262,
         -0.01475636, -0.04662099,  0.03580693,  0.01218406,
          0.04421878, -0.00967856],
        [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262,
         -0.01475636, -0.04662099,  0.03580693,  0.01218406,
          0.04421878, -0.00967856],
        [ 0.0002228 , -0.02179424,  0.02515132,  0.03432262,
         -0.01475636, -0.04662099,  0.03580693,  0.01218406,
          0.04421878, -0.00967856],
        [ 0.04556483,  0.0287129 , -0.0244712 ,  0.04458561,
         -0.01200197, -0.0093414 , -0.03454223, -0.03976092,
          0.04076023, -0.04271444],
        [-0.00312374,  0.03127487,  0.04706002,  0.04473511,
         -0.02143162, -0.04631407, -0.02680214, -0.0285754 ,
          0.01728689, -0.00047459],
        [-0.00547457, -0.03071852,  0.00469918,  0.0